from collections.abc import Mapping
from os import PathLike

from ...core.atomic import Element

_Path = str | PathLike[str]
_Rate = dict[str, object]

def add_line_power_rate(species: Element, charge: int, rate: Mapping[str, object], repository_path: _Path | None = None) -> None: ...
def update_line_power_rates(rates: Mapping[object, object], repository_path: _Path | None = None) -> None: ...
def add_continuum_power_rate(species: Element, charge: int, rate: Mapping[str, object], repository_path: _Path | None = None) -> None: ...
def update_continuum_power_rates(rates: Mapping[object, object], repository_path: _Path | None = None) -> None: ...
def add_cx_power_rate(species: Element, charge: int, rate: Mapping[str, object], repository_path: _Path | None = None) -> None: ...
def update_cx_power_rates(rates: Mapping[object, object], repository_path: _Path | None = None) -> None: ...
def get_line_radiated_power_rate(element: Element, charge: int, repository_path: _Path | None = None) -> _Rate: ...
def get_continuum_radiated_power_rate(element: Element, charge: int, repository_path: _Path | None = None) -> _Rate: ...
def get_cx_radiated_power_rate(element: Element, charge: int, repository_path: _Path | None = None) -> _Rate: ...
