from collections.abc import Callable, Iterable
from typing import SupportsIndex, TypeVar

_T = TypeVar("_T")
_Callback = Callable[[], object]

class Notifier:
    def __init__(self) -> None: ...
    def add(self, callback: _Callback) -> None: ...
    def remove(self, callback: _Callback) -> None: ...
    def is_present(self, callback: _Callback) -> bool: ...
    def notify(self) -> None: ...

class NotifyingList(list[_T]):
    def __init__(self, iterable: Iterable[_T] = (), /) -> None: ...
    @property
    def notifier(self) -> Notifier: ...
    def append(self, p_object: _T) -> None: ...
    def insert(self, index: SupportsIndex, p_object: _T) -> None: ...
    def extend(self, iterable: Iterable[_T]) -> None: ...
    def pop(self, index: SupportsIndex = -1) -> _T: ...
    def remove(self, value: _T) -> None: ...
