from abc import ABCMeta
from collections.abc import Mapping, Sequence
from typing import ClassVar

from raysect.core import AffineMatrix3D, Node
from raysect.core.scenegraph._nodebase import _NodeBase
from raysect.core.workflow import RenderEngine
from raysect.optical.observer import Observer0D
from raysect.optical.observer.base import Pipeline0D

class Observer0DGroup(Node, metaclass=ABCMeta):
    _OBSERVER_TYPE: ClassVar[type[Observer0D]] = Observer0D
    _observers: list[Observer0D]
    def __init__(
        self,
        parent: _NodeBase | None = None,
        transform: AffineMatrix3D | None = None,
        name: str | None = None,
        observers: Sequence[Observer0D] | None = None,
    ) -> None: ...
    def __getitem__(self, item: int) -> Observer0D: ...
    def __len__(self) -> int: ...
    @property
    def observers(self) -> tuple[Observer0D, ...]: ...
    @observers.setter
    def observers(self, value: Sequence[Observer0D]) -> None: ...
    def add_observer(self, observer: Observer0D) -> None: ...
    @property
    def names(self) -> list[str]: ...
    @names.setter
    def names(self, value: Sequence[str]) -> None: ...
    def observe(self) -> None: ...
    @property
    def render_engine(self) -> RenderEngine | list[RenderEngine]: ...
    @render_engine.setter
    def render_engine(self, value: RenderEngine | Sequence[RenderEngine]) -> None: ...
    @property
    def spectral_bins(self) -> int | list[int]: ...
    @spectral_bins.setter
    def spectral_bins(self, value: int | Sequence[int]) -> None: ...
    @property
    def spectral_rays(self) -> int | list[int]: ...
    @spectral_rays.setter
    def spectral_rays(self, value: int | Sequence[int]) -> None: ...
    @property
    def max_wavelength(self) -> float | list[float]: ...
    @max_wavelength.setter
    def max_wavelength(self, value: float | Sequence[float]) -> None: ...
    @property
    def min_wavelength(self) -> float | list[float]: ...
    @min_wavelength.setter
    def min_wavelength(self, value: float | Sequence[float]) -> None: ...
    @property
    def ray_extinction_prob(self) -> float | list[float]: ...
    @ray_extinction_prob.setter
    def ray_extinction_prob(self, value: float | Sequence[float]) -> None: ...
    @property
    def ray_max_depth(self) -> int | list[int]: ...
    @ray_max_depth.setter
    def ray_max_depth(self, value: int | Sequence[int]) -> None: ...
    @property
    def ray_extinction_min_depth(self) -> int | list[int]: ...
    @ray_extinction_min_depth.setter
    def ray_extinction_min_depth(self, value: int | Sequence[int]) -> None: ...
    @property
    def ray_importance_sampling(self) -> bool | list[bool]: ...
    @ray_importance_sampling.setter
    def ray_importance_sampling(self, value: bool | Sequence[bool]) -> None: ...
    @property
    def ray_important_path_weight(self) -> float | list[float]: ...
    @ray_important_path_weight.setter
    def ray_important_path_weight(self, value: float | Sequence[float]) -> None: ...
    @property
    def quiet(self) -> bool | list[bool]: ...
    @quiet.setter
    def quiet(self, value: bool | Sequence[bool]) -> None: ...
    @property
    def pixel_samples(self) -> int | list[int]: ...
    @pixel_samples.setter
    def pixel_samples(self, value: int | Sequence[int]) -> None: ...
    @property
    def samples_per_task(self) -> int | list[int]: ...
    @samples_per_task.setter
    def samples_per_task(self, value: int | Sequence[int]) -> None: ...
    @property
    def pipelines(self) -> list[list[Pipeline0D]]: ...
    @pipelines.setter
    def pipelines(self, pipelist: Sequence[Sequence[Pipeline0D]]) -> None: ...
    def connect_pipelines(
        self,
        pipeline_classes: Sequence[type[Pipeline0D]],
        keywords_list: Sequence[Mapping[str, object]] | None = None,
        suppress_display_progress: bool = True,
    ) -> None: ...
