from raysect.core.math import Point3D, Vector3D
from raysect.optical import Spectrum

from ..atomic import AtomicData
from ..plasma import Plasma
from ..utility.notify import Notifier
from .node import Beam

class BeamModel:
    def __init__(self) -> None: ...
    @property
    def plasma(self) -> Plasma | None: ...
    @plasma.setter
    def plasma(self, value: Plasma | None) -> None: ...
    @property
    def beam(self) -> Beam | None: ...
    @beam.setter
    def beam(self, value: Beam | None) -> None: ...
    @property
    def atomic_data(self) -> AtomicData | None: ...
    @atomic_data.setter
    def atomic_data(self, value: AtomicData | None) -> None: ...
    def emission(
        self,
        beam_point: Point3D,
        plasma_point: Point3D,
        beam_direction: Vector3D,
        observation_direction: Vector3D,
        spectrum: Spectrum,
    ) -> Spectrum: ...
    def _change(self) -> None: ...

class BeamAttenuator:
    notifier: Notifier
    def __init__(self) -> None: ...
    @property
    def plasma(self) -> Plasma | None: ...
    @plasma.setter
    def plasma(self, value: Plasma | None) -> None: ...
    @property
    def beam(self) -> Beam | None: ...
    @beam.setter
    def beam(self, value: Beam | None) -> None: ...
    @property
    def atomic_data(self) -> AtomicData | None: ...
    @atomic_data.setter
    def atomic_data(self, value: AtomicData | None) -> None: ...
    def density(self, x: float, y: float, z: float) -> float: ...
    def _change(self) -> None: ...
